# Generated by Django 2.0.3 on 2018-03-14 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubukprn', models.CharField(max_length=25)),
                ('ukprn', models.CharField(max_length=25)),
                ('kiscourseid', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=100)),
                ('mode', models.CharField(choices=[('1', 'Full-time'), ('2', 'Part-time'), ('3', 'Both')], default='1', max_length=1)),
                ('distance', models.CharField(choices=[('0', 'Course is available other than by distance learning'), ('1', 'Course is only available through distance learning'), ('2', 'Course is optionally available through distance learning')], default='0', max_length=1)),
                ('aim', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locid', models.CharField(max_length=2)),
                ('ukprn', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('XF', 'England'), ('XG', 'Northern Ireland'), ('XH', 'Scotland'), ('XI', 'Wales'), ('XK', 'United Kingdom')], default='XK', max_length=2)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('locid', 'ukprn')},
        ),
        migrations.AddField(
            model_name='course',
            name='jobs',
            field=models.ManyToManyField(to='coursefinderapp.Job'),
        ),
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coursefinderapp.Location'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('pubukprn', 'ukprn', 'kiscourseid', 'mode')},
        ),
    ]
